Cable line dev
somal/CenterNet pull request #2
Opened 2021-10-07 06:47 UTC by vspavl99

2021-10-07 10:38 UTC, somal requested changes

2021-10-07 10:38 UTC, somal commented on ConnectingToServer.md
> +docker build --tag center_net_env --file test/DockerCenterNet/CenterNet.dockerfile .
Нужно ли его собирать каждый раз?
Где этот файл?

2021-10-07 10:38 UTC, somal commented on ConnectingToServer.md
> +apt update && apt install -y openssh-server
Мб это запихнуть в Dockerfile?

2021-10-07 10:38 UTC, somal commented on ConnectingToServer.md
> +ssh -L 8022:192.168.0.55:8022 vpavlishen@195.91.176.132
Не стоит оставлять свои credentials

2021-10-07 10:38 UTC, somal commented on ConnectingToServer.md
> +docker build --tag center_net_env --file test/DockerCenterNet/CenterNet.dockerfile .
Там есть какие-то зависимости CenterNet? 
Если нет, то может сделать общий контейнер?

2021-10-07 10:38 UTC, somal commented on ConnectingToServer.md
> +docker run --gpus all -it --rm -p 8022:22 -v /home/vpavlishen/CenterNet:/home/test --name center_net_env_ssh center_net_env_ssh bash
Для полноценного доступа нужно везде поставить общий доступ (положить в отдельную папку)

2021-10-07 10:38 UTC, somal commented on ConnectingToServer.md
> +6.  ssh tunnel
```suggestion
6.  ssh tunnel (on own machine)
```

2021-10-07 10:38 UTC, somal commented on ConnectingToServer.md
> +7. Connect to python interpreter through ssh tunnel.
Какой логин доступа для localhost:8022?

2021-10-07 10:38 UTC, somal commented on src/lib/datasets/check_riders_and_miners.py
> +import ast
Здесь вроде все ок, но лучше пути вытаскивать в параметры и лучше эти изменения вытащить в ветку этого репозитория

2021-10-11 11:56 UTC, vspavl99 commented on ConnectingToServer.md
> +docker build --tag center_net_env --file test/DockerCenterNet/CenterNet.dockerfile .
После выполнения шагов 1-4.  Не нужно пересобирать каждый раз, можно всегда сразу начинать с 5 шага.

2021-10-11 11:58 UTC, vspavl99 commented on ConnectingToServer.md
> +docker build --tag center_net_env --file test/DockerCenterNet/CenterNet.dockerfile .
Файл лежит в /home/ftp-user/share/Victor/DockerCenterNet

2021-10-11 11:58 UTC, vspavl99 commented on ConnectingToServer.md
> +docker build --tag center_net_env --file test/DockerCenterNet/CenterNet.dockerfile .
Зависимостей для CenterNet нет, так что контейнер можно считать общим

2021-10-11 11:59 UTC, vspavl99 commented on ConnectingToServer.md
> +7. Connect to python interpreter through ssh tunnel.
логин указывается в пункте 2.

2021-10-11 12:34 UTC, somal commented on ConnectingToServer.md
> +docker build --tag center_net_env --file test/DockerCenterNet/CenterNet.dockerfile .
Обсудили голосом

2021-10-11 12:36 UTC, somal commented on ConnectingToServer.md
> +apt update && apt install -y openssh-server
Решили, что уберем пароль вообще и засунем внутрь файла

2021-10-11 12:38 UTC, somal commented on ConnectingToServer.md
> +docker run --gpus all -it --rm -p 8022:22 -v /home/vpavlishen/CenterNet:/home/test --name center_net_env_ssh center_net_env_ssh bash
+Описать работу с volume

2021-10-18 10:50 UTC, merged